# Generated by Django 2.1.4 on 2018-12-18 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0003_auto_20181214_1402'),
        ('users', '0002_remove_userprofile_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Профіль користувача', 'verbose_name_plural': 'Профіль користувача'},
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='phone.Phone'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(max_length=30, verbose_name="Ім'я"),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(max_length=40, verbose_name='Призвище'),
        ),
    ]
