# Generated by Django 2.1.2 on 2018-12-06 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Battary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Батарея',
                'verbose_name_plural': 'Батарея',
            },
        ),
        migrations.CreateModel(
            name='Cam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Камера',
                'verbose_name_plural': 'Камера',
            },
        ),
        migrations.CreateModel(
            name='Coefficient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coeff', models.DecimalField(decimal_places=5, max_digits=10, max_length=30)),
            ],
            options={
                'verbose_name': 'Коэффициент',
                'verbose_name_plural': 'Коэффициенты',
            },
        ),
        migrations.CreateModel(
            name='CPU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=14)),
                ('coefficient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phone.Coefficient')),
            ],
            options={
                'verbose_name': 'Процессор',
                'verbose_name_plural': 'Процессор',
            },
        ),
        migrations.CreateModel(
            name='Manufacture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('coefficient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phone.Coefficient')),
            ],
            options={
                'verbose_name': 'Производитель',
                'verbose_name_plural': 'Производитель',
            },
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('battary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phone.Battary')),
                ('cam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phone.Cam')),
                ('cpu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phone.CPU')),
                ('manufacture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phone.Manufacture')),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=5, max_digits=10, max_length=30)),
                ('coefficient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phone.Coefficient')),
            ],
        ),
        migrations.CreateModel(
            name='ROM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('coefficient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phone.Coefficient')),
            ],
            options={
                'verbose_name': 'Оперативная память',
                'verbose_name_plural': 'Оперативная память',
            },
        ),
        migrations.CreateModel(
            name='Screen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('coefficient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phone.Coefficient')),
            ],
            options={
                'verbose_name': 'Экран',
                'verbose_name_plural': 'Экран',
            },
        ),
        migrations.AddField(
            model_name='phone',
            name='price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phone.Price'),
        ),
        migrations.AddField(
            model_name='phone',
            name='rom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phone.ROM'),
        ),
        migrations.AddField(
            model_name='phone',
            name='screen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phone.Screen'),
        ),
        migrations.AddField(
            model_name='cam',
            name='coefficient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phone.Coefficient'),
        ),
        migrations.AddField(
            model_name='battary',
            name='coefficient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phone.Coefficient'),
        ),
    ]
