# Generated by Django 2.1.2 on 2018-11-28 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Battary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=7)),
            ],
            options={
                'verbose_name': 'Батарея',
                'verbose_name_plural': 'Батарея',
            },
        ),
        migrations.CreateModel(
            name='Cam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2)),
            ],
            options={
                'verbose_name': 'Камера',
                'verbose_name_plural': 'Камера',
            },
        ),
        migrations.CreateModel(
            name='CPU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=14)),
            ],
            options={
                'verbose_name': 'Процессор',
                'verbose_name_plural': 'Процессор',
            },
        ),
        migrations.CreateModel(
            name='Manufacture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name': 'Производитель',
                'verbose_name_plural': 'Производитель',
            },
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('battary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phone.Battary')),
                ('cam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phone.Cam')),
                ('cpu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phone.CPU')),
                ('manufacture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phone.Manufacture')),
            ],
        ),
        migrations.CreateModel(
            name='ROM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Оперативная память',
                'verbose_name_plural': 'Оперативная память',
            },
        ),
        migrations.CreateModel(
            name='Screen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2)),
            ],
            options={
                'verbose_name': 'Экран',
                'verbose_name_plural': 'Экран',
            },
        ),
        migrations.CreateModel(
            name='ValueWeight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=3, max_digits=5)),
            ],
        ),
        migrations.AddField(
            model_name='screen',
            name='weight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phone.ValueWeight'),
        ),
        migrations.AddField(
            model_name='rom',
            name='weight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phone.ValueWeight'),
        ),
        migrations.AddField(
            model_name='phone',
            name='rom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phone.ROM'),
        ),
        migrations.AddField(
            model_name='phone',
            name='screen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phone.Screen'),
        ),
        migrations.AddField(
            model_name='manufacture',
            name='weight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phone.ValueWeight'),
        ),
        migrations.AddField(
            model_name='cpu',
            name='weight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phone.ValueWeight'),
        ),
        migrations.AddField(
            model_name='cam',
            name='weight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phone.ValueWeight'),
        ),
        migrations.AddField(
            model_name='battary',
            name='weight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phone.ValueWeight'),
        ),
    ]
