# Generated by Django 2.1.2 on 2018-12-03 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='valueweight',
            name='total',
            field=models.DecimalField(decimal_places=5, default='55.00', max_digits=10, max_length=30),
            preserve_default=False,
        ),
    ]
